// Denní modlitby (du'a) z islámské tradice
export const prayers = {
  ar: [
    "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى",
    "اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ",
    "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ",
    "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي",
    "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَأَعُوذُ بِكَ مِنَ النَّارِ",
    "اللَّهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ، دِقَّهُ وَجِلَّهُ، وَأَوَّلَهُ وَآخِرَهُ",
    "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ جَهْدِ الْبَلَاءِ، وَدَرَكِ الشَّقَاءِ",
    "رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِن ذُرِّيَّتِي",
    "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، وَمِنْ عَذَابِ جَهَنَّمَ",
    "اللَّهُمَّ ثَبِّتْنِي عِنْدَ الْمَسْأَلَةِ",
    "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ",
    "رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ",
    "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكَسَلِ وَالْهَرَمِ",
    "اللَّهُمَّ أَصْلِحْ لِي دِينِي الَّذِي هُوَ عِصْمَةُ أَمْرِي",
    "رَبِّ زِدْنِي عِلْمًا وَارْزُقْنِي فَهْمًا",
    "اللَّهُمَّ إِنِّي أَسْأَلُكَ حُبَّكَ وَحُبَّ مَنْ يُحِبُّكَ",
    "اللَّهُمَّ بَارِكْ لِي فِيمَا رَزَقْتَنِي",
    "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا",
    "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عِلْمٍ لَا يَنْفَعُ",
  ],
  
  en: [
    "Our Lord, give us in this world good and in the Hereafter good and protect us from the punishment of the Fire.",
    "O Allah, I ask You for guidance, piety, chastity, and self-sufficiency.",
    "O Allah, help me remember You, thank You, and worship You well.",
    "O Allah, I seek refuge in You from anxiety and grief, from incapacity and laziness.",
    "My Lord, expand my chest and ease my task.",
    "O Allah, I ask You for Paradise and seek refuge in You from the Fire.",
    "O Allah, forgive me all my sins, the small and great, the first and last.",
    "O Allah, I seek refuge in You from the hardship of trial and the misery of misfortune.",
    "My Lord, make me an establisher of prayer, and also from my offspring.",
    "O Allah, I seek refuge in You from the punishment of the grave and the punishment of Hellfire.",
    "O Allah, make me steadfast at the moment of questioning.",
    "O Allah, I ask You for pardon and well-being in this world and the Hereafter.",
    "Our Lord, accept from us. Indeed, You are the All-Hearing, the All-Knowing.",
    "O Allah, I seek refuge in You from laziness and senility.",
    "O Allah, rectify my religion which is the safeguard of my affairs.",
    "My Lord, increase me in knowledge and grant me understanding.",
    "O Allah, I ask You for Your love and the love of those who love You.",
    "O Allah, bless me in what You have provided me.",
    "Our Lord, do not let our hearts deviate after You have guided us.",
    "O Allah, I seek refuge in You from knowledge that does not benefit.",
  ],
  
  ur: [
    "اے ہمارے رب! ہمیں دنیا میں بھی بھلائی دے اور آخرت میں بھی بھلائی دے اور ہمیں دوزخ کے عذاب سے بچا",
    "اے اللہ! میں تجھ سے ہدایت، پرہیزگاری، پاکدامنی اور بے نیازی مانگتا ہوں",
    "اے اللہ! میری مدد فرما اپنے ذکر، اپنے شکر اور اچھی عبادت پر",
    "اے اللہ! میں تیری پناہ مانگتا ہوں فکر و غم سے، عاجزی و سستی سے",
    "اے میرے رب! میرا سینہ کھول دے اور میرا کام آسان کر دے",
    "اے اللہ! میں تجھ سے جنت مانگتا ہوں اور جہنم سے تیری پناہ مانگتا ہوں",
    "اے اللہ! میرے سارے گناہ معاف فرما، چھوٹے اور بڑے، پہلے اور پچھلے",
    "اے اللہ! میں تیری پناہ مانگتا ہوں سخت آزمائش سے اور بری مصیبت سے",
    "اے میرے رب! مجھے نماز قائم کرنے والا بنا اور میری اولاد کو بھی",
    "اے اللہ! میں تیری پناہ مانگتا ہوں قبر کے عذاب سے اور جہنم کے عذاب سے",
    "اے اللہ! مجھے سوال کے وقت ثابت قدم رکھ",
    "اے اللہ! میں تجھ سے معافی اور عافیت مانگتا ہوں دنیا اور آخرت میں",
    "اے ہمارے رب! ہم سے قبول فرما، بے شک تو سننے والا جاننے والا ہے",
    "اے اللہ! میں تیری پناہ مانگتا ہوں سستی اور بڑھاپے سے",
    "اے اللہ! میرے دین کی اصلاح فرما جو میرے معاملات کی حفاظت ہے",
    "اے میرے رب! مجھے علم میں اضافہ فرما اور سمجھ عطا فرما",
    "اے اللہ! میں تجھ سے تیری محبت مانگتا ہوں اور ان کی محبت جو تجھ سے محبت کرتے ہیں",
    "اے اللہ! مجھے برکت دے جو تو نے مجھے دیا ہے",
    "اے ہمارے رب! ہمارے دلوں کو ٹیڑھا نہ کر بعد اس کے کہ تو نے ہمیں ہدایت دی",
    "اے اللہ! میں تیری پناہ مانگتا ہوں اس علم سے جو فائدہ نہ دے",
  ],
};