// Denní verše z Koránu pro různé jazyky
export const dailyVerses = {
  ar: [
    { text: "إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ", reference: "الرعد ١١" },
    { text: "وَلَا تَيْأَسُوا مِن رَّوْحِ اللَّهِ ۖ إِنَّهُ لَا يَيْأَسُ مِن رَّوْحِ اللَّهِ إِلَّا الْقَوْمُ الْكَافِرُونَ", reference: "يوسف ٨٧" },
    { text: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ", reference: "البقرة ٢٠١" },
    { text: "إِنَّ مَعَ الْعُسْرِ يُسْرًا", reference: "الشرح ٦" },
    { text: "وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ", reference: "الطلاق ٢-٣" },
    { text: "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا", reference: "البقرة ٢٨٦" },
    { text: "إِنَّ اللَّهَ يُحِبُّ الْمُحْسِنِينَ", reference: "البقرة ١٩٥" },
    { text: "وَاصْبِرْ ۖ إِنَّ اللَّهَ مَعَ الصَّابِرِينَ", reference: "الأنفال ٤٦" },
    { text: "رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا", reference: "الإسراء ٢٤" },
    { text: "وَلَا تَحْسَبَنَّ اللَّهَ غَافِلًا عَمَّا يَعْمَلُ الظَّالِمُونَ", reference: "إبراهيم ٤٢" },
    { text: "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَىٰ دِينِكَ", reference: "آل عمران ٨" },
    { text: "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي", reference: "طه ٢٥-٢٦" },
    { text: "وَعَسَىٰ أَن تَكْرَهُوا شَيْئًا وَهُوَ خَيْرٌ لَّكُمْ", reference: "البقرة ٢١٦" },
    { text: "فَإِنَّ مَعَ الْعُسْرِ يُسْرًا إِنَّ مَعَ الْعُسْرِ يُسْرًا", reference: "الشرح ٥-٦" },
    { text: "قُلْ إِنَّ صَلَاتِي وَنُسُكِي وَمَحْيَايَ وَمَمَاتِي لِلَّهِ رَبِّ الْعَالَمِينَ", reference: "الأنعام ١٦٢" },
    { text: "وَمَنْ أَحْسَنُ قَوْلًا مِّمَّن دَعَا إِلَى اللَّهِ وَعَمِلَ صَالِحًا", reference: "فصلت ٣٣" },
    { text: "رَبَّنَا اغْفِرْ لَنَا ذُنُوبَنَا وَإِسْرَافَنَا فِي أَمْرِنَا", reference: "آل عمران ١٤٧" },
    { text: "إِنَّ اللَّهَ لَا يُضِيعُ أَجْرَ الْمُحْسِنِينَ", reference: "التوبة ١٢٠" },
    { text: "وَتَوَكَّلْ عَلَى الْحَيِّ الَّذِي لَا يَمُوتُ", reference: "الفرقان ٥٨" },
    { text: "رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَتَوَفَّنَا مُسْلِمِينَ", reference: "الأعراف ١٢٦" },
  ],
  
  en: [
    { text: "Indeed, Allah will not change the condition of a people until they change what is in themselves.", reference: "Ar-Ra'd 11" },
    { text: "Do not despair of the mercy of Allah. Indeed, Allah forgives all sins.", reference: "Az-Zumar 53" },
    { text: "Our Lord, give us in this world good and in the Hereafter good and protect us from the punishment of the Fire.", reference: "Al-Baqarah 201" },
    { text: "Indeed, with hardship comes ease.", reference: "Ash-Sharh 6" },
    { text: "And whoever fears Allah, He will make a way out for him and provide for him from where he does not expect.", reference: "At-Talaq 2-3" },
    { text: "Allah does not burden a soul beyond that it can bear.", reference: "Al-Baqarah 286" },
    { text: "Indeed, Allah loves the doers of good.", reference: "Al-Baqarah 195" },
    { text: "Be patient; indeed, Allah is with the patient.", reference: "Al-Anfal 46" },
    { text: "My Lord, have mercy upon them as they brought me up when I was small.", reference: "Al-Isra 24" },
    { text: "And never think that Allah is unaware of what the wrongdoers do.", reference: "Ibrahim 42" },
    { text: "O Turner of hearts, keep my heart firm upon Your religion.", reference: "Ali 'Imran 8" },
    { text: "My Lord, expand for me my chest and ease for me my task.", reference: "Ta-Ha 25-26" },
    { text: "But perhaps you hate a thing and it is good for you.", reference: "Al-Baqarah 216" },
    { text: "For indeed, with hardship comes ease. Indeed, with hardship comes ease.", reference: "Ash-Sharh 5-6" },
    { text: "Say: Indeed, my prayer, my rites, my life and my death are for Allah, Lord of the worlds.", reference: "Al-An'am 162" },
    { text: "And who is better in speech than one who invites to Allah and does righteousness?", reference: "Fussilat 33" },
    { text: "Our Lord, forgive us our sins and our excess in our affairs.", reference: "Ali 'Imran 147" },
    { text: "Indeed, Allah does not allow the reward of the doers of good to be lost.", reference: "At-Tawbah 120" },
    { text: "And rely upon the Ever-Living who does not die.", reference: "Al-Furqan 58" },
    { text: "Our Lord, pour upon us patience and cause us to die as Muslims.", reference: "Al-A'raf 126" },
  ],
  
  ur: [
    { text: "بے شک اللہ کسی قوم کی حالت نہیں بدلتا جب تک وہ خود اپنی حالت نہ بدلیں", reference: "الرعد ۱۱" },
    { text: "اللہ کی رحمت سے مایوس نہ ہو، بے شک اللہ سارے گناہ معاف کر دیتا ہے", reference: "الزمر ۵۳" },
    { text: "اے ہمارے رب! ہمیں دنیا میں بھی بھلائی دے اور آخرت میں بھی بھلائی دے", reference: "البقرہ ۲۰۱" },
    { text: "بے شک مشکل کے ساتھ آسانی ہے", reference: "الشرح ۶" },
    { text: "جو اللہ سے ڈرے گا اللہ اس کے لیے راستہ نکالے گا اور اسے ایسی جگہ سے رزق دے گا جس کا اسے گمان بھی نہ ہو", reference: "الطلاق ۲-۳" },
    { text: "اللہ کسی جان کو اس کی طاقت سے زیادہ تکلیف نہیں دیتا", reference: "البقرہ ۲۸۶" },
    { text: "بے شک اللہ نیکی کرنے والوں سے محبت کرتا ہے", reference: "البقرہ ۱۹۵" },
    { text: "صبر کرو، بے شک اللہ صبر کرنے والوں کے ساتھ ہے", reference: "الأنفال ۴۶" },
    { text: "اے میرے رب! ان پر رحم فرما جیسے انہوں نے مجھے بچپن میں پالا", reference: "الإسراء ۲۴" },
    { text: "اور یہ مت سمجھو کہ اللہ ظالموں کے کاموں سے غافل ہے", reference: "ابراہیم ۴۲" },
    { text: "اے دلوں کے پھیرنے والے! میرے دل کو اپنے دین پر ثابت رکھ", reference: "آل عمران ۸" },
    { text: "اے میرے رب! میرا سینہ کھول دے اور میرا کام آسان کر دے", reference: "طه ۲۵-۲۶" },
    { text: "ہو سکتا ہے تم کسی چیز کو ناپسند کرو اور وہ تمہارے لیے بہتر ہو", reference: "البقرہ ۲۱۶" },
    { text: "پس یقیناً مشکل کے ساتھ آسانی ہے، یقیناً مشکل کے ساتھ آسانی ہے", reference: "الشرح ۵-۶" },
    { text: "کہہ دیجئے کہ میری نماز، میری قربانی، میری زندگی اور میری موت اللہ رب العالمین کے لیے ہے", reference: "الأنعام ۱۶۲" },
    { text: "اور اس سے بہتر بات کس کی ہو سکتی ہے جو اللہ کی طرف بلائے اور نیک عمل کرے", reference: "فصلت ۳۳" },
    { text: "اے ہمارے رب! ہمارے گناہ معاف فرما اور ہمارے کاموں میں ہماری زیادتی بھی معاف فرما", reference: "آل عمران ۱۴۷" },
    { text: "بے شک اللہ نیکی کرنے والوں کا اجر ضائع نہیں کرتا", reference: "التوبہ ۱۲۰" },
    { text: "اور اس زندہ پر بھروسہ کرو جو کبھی نہیں مرتا", reference: "الفرقان ۵۸" },
    { text: "اے ہمارے رب! ہم پر صبر انڈیل دے اور ہمیں مسلمان موت دے", reference: "الأعراف ۱۲۶" },
  ],
};